## BÀI 1: LÀM QUEN VỚI PYTORCH

#### Bài 1. Tạo Tensor cơ bản

In [46]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Bài 2. Tạo các Tensor thường dùng

In [47]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)

f = torch.full((5, 5), 10 )
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)


tensor([[0.7988, 0.3150, 0.0077, 0.6604],
        [0.7456, 0.7904, 0.8412, 0.4894],
        [0.3438, 0.7689, 0.9789, 0.9050]])
tensor([[-0.0552, -0.6351, -0.1046,  1.2365],
        [ 1.4042,  0.9568, -0.4722,  2.2062],
        [-1.0412, -0.0635,  0.1976,  0.5137]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


#### Bài 3. Kiểm tra thông tin Tensor

In [48]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


torch.Size([2, 3, 4]) có nghĩa là tensor có 3 chiều (3D):
2 là 2 khối ,
3 là mỗi khối 3 hàng,
4 là mỗi hàng 4 phần tử.

#### Bài 4. Slicing và Indexing


In [49]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])
print("\nTensor a[:,: ,-2:]:")
print(a[:,:,-2:])

Original tensor:
tensor([[[ 0.7919, -0.4331, -0.7861, -0.6129, -0.3990],
         [-0.2697,  3.6188, -1.0266,  1.4262,  0.3942],
         [ 0.7708,  0.9003,  1.3077,  0.7350,  0.3303],
         [ 0.0768,  1.2943,  0.5031,  2.0552, -0.0461]],

        [[ 1.1042, -0.3374, -1.0607,  0.4718,  0.7189],
         [-1.9179,  0.8559,  1.9108, -1.1287, -1.0346],
         [-2.3114, -0.0579, -0.7944, -1.6996, -0.7036],
         [-0.8034,  0.8071, -0.1949, -0.3461,  0.4126]],

        [[-1.1687,  1.0878,  0.7799, -1.2028, -0.8394],
         [ 0.1782,  1.4106,  1.6576, -1.6041, -0.3982],
         [-0.6567,  0.8914, -0.0999, -0.7966,  0.9125],
         [-1.4845,  0.2444, -1.8220, -1.9815, -0.1550]]])

Tensor a[1]:
tensor([[ 1.1042, -0.3374, -1.0607,  0.4718,  0.7189],
        [-1.9179,  0.8559,  1.9108, -1.1287, -1.0346],
        [-2.3114, -0.0579, -0.7944, -1.6996, -0.7036],
        [-0.8034,  0.8071, -0.1949, -0.3461,  0.4126]])

Tensor a[1:, 2:4]:
tensor([[[-2.3114, -0.0579, -0.7944, -1.6996, -0.7

a.shape=torch.Size([3,4,5])

a[1].shape=torch.Size([4,5])
4 hàng 
5 cột

a[1:, 2:4].shape = torch.Size([2, 2, 5])

1: lấy khối index 1 và 2 là 2 khối,
2:4 lấy hàng index 2 và 3 là 2 hàng,
Không cắt chiều cuối lấy đủ 5 cột

#### Bài 5. Reshape và Flatten

In [50]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-1.2248, -0.3025, -0.9193,  0.8819],
        [-0.6026,  0.3315,  0.7583,  1.5715],
        [ 0.2175,  0.4315,  0.4633, -0.0944]])

Flatten:
tensor([-1.2248, -0.3025, -0.9193,  0.8819, -0.6026,  0.3315,  0.7583,  1.5715,
         0.2175,  0.4315,  0.4633, -0.0944])

Reshape to 3 x 2 x 2:
tensor([[[-1.2248, -0.3025],
         [-0.9193,  0.8819]],

        [[-0.6026,  0.3315],
         [ 0.7583,  1.5715]],

        [[ 0.2175,  0.4315],
         [ 0.4633, -0.0944]]])


số phần tử trước và sau reshape không thay đổi chỉ thay đổi chiều và vị trí sắp xếp
 

In [51]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 2 x 6:")
print(a.reshape(2,6))

Original:
tensor([[-1.0301,  1.0318, -0.6039, -1.8356],
        [-0.8095, -0.9174,  1.7774, -0.4949],
        [ 0.3425,  0.0693, -0.5553, -0.2638]])

Flatten:
tensor([-1.0301,  1.0318, -0.6039, -1.8356, -0.8095, -0.9174,  1.7774, -0.4949,
         0.3425,  0.0693, -0.5553, -0.2638])

Reshape to 2 x 6:
tensor([[-1.0301,  1.0318, -0.6039, -1.8356, -0.8095, -0.9174],
        [ 1.7774, -0.4949,  0.3425,  0.0693, -0.5553, -0.2638]])


#### Bài 6. Phép toán và nhân ma trận

In [52]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\na * b:")
print(a * b)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[-0.0338,  0.6802,  1.1827],
        [-0.1567, -0.8632, -0.1915]])
b:
tensor([[ 0.1760, -0.5437,  1.1711],
        [-0.5749, -0.2831, -0.4440]])

a + b:
tensor([[ 0.1422,  0.1365,  2.3537],
        [-0.7316, -1.1463, -0.6354]])

a / b:
tensor([[-0.1919, -1.2510,  1.0099],
        [ 0.2725,  3.0486,  0.4313]])

a^2:
tensor([[1.1400e-03, 4.6261e-01, 1.3987e+00],
        [2.4548e-02, 7.4504e-01, 3.6657e-02]])

a * b:
tensor([[-0.0059, -0.3698,  1.3850],
        [ 0.0901,  0.2444,  0.0850]])

Matrix multiplication:
tensor([[ 1.0092, -0.6982],
        [ 0.2175,  0.4195]])


##### a*b là nhân từng phần tử 
##### a @ b.T là nhân ma trận a vơi ma trận chuyển vị của b

##### a @ b.T = torch.Size([2,2])

#### Bài 7. Các hàm thống kê trên Tensor


In [53]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-0.6552, -0.3692, -1.1414,  0.2090],
        [-0.5847, -1.0816,  0.2840, -0.4619],
        [-0.6381, -0.3902,  2.5247, -1.0424]])

Mean:
tensor([-0.6260, -0.6137,  0.5558, -0.4318])

Standard deviation:
tensor([0.0368, 0.4054, 1.8481, 0.6263])

Cumulative sum:
tensor([[-0.6552, -0.3692, -1.1414,  0.2090],
        [-1.2399, -1.4508, -0.8574, -0.2530],
        [-1.8781, -1.8410,  1.6673, -1.2954]])


thay dim=1

In [54]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[ 0.2340, -0.3486, -0.9262,  2.2426],
        [ 1.3199,  1.7348,  0.2419,  0.2812],
        [-0.3249, -1.9523, -1.7985, -0.0341]])

Mean:
tensor([ 0.3005,  0.8945, -1.0274])

Standard deviation:
tensor([1.3787, 0.7503, 0.9883])

Cumulative sum:
tensor([[ 0.2340, -0.1146, -1.0408,  1.2019],
        [ 1.3199,  3.0547,  3.2966,  3.5778],
        [-0.3249, -2.2772, -4.0756, -4.1098]])


Mean và Standard deviation: giảm 1 phần tử so với dim =0

Cumulative sum: số lượng phần tử không đổi
